
- hosts: ubuntu_hosts
  remote_user: manage
  become: true
  #become_pass: 123456
  become_method: sudo
  become_user: root

  tasks:

    - name: Check if host exists
      become_user: oneadmin
      become_method: sudo
      shell: "onehost list --list NAME | grep 'localhost'"
      register: result
      ignore_errors: True
    
    - name: Create Host
      command: onehost create localhost --im kvm --vm kvm
      when: result|failed

#    - name: Copy VM Image 1
#      become_user: oneadmin
#      copy:
##        remote_src: true
#        src: /home/manage/One_Files/Images/f7459d3fe8f0cc272fe9cd6a9b6edab3
#        dest: /var/lib/one/datastores/1/

    - name: Copy VM Image 2
      copy:
#        remote_src: true
        src: /home/manage/One_Files/Images/39745246d90aab23c3434be0c9e159c5
        dest: /var/lib/one/datastores/1/
 
    - name: Copy VNet Templates
      copy:
        src: /home/manage/One_Files/VNets/
        dest: /home/manage

    - name: Check if Virtual Network Templates exist
      become_user: oneadmin
      become_method: sudo
      shell: "onevnet list --list NAME | grep 'Public'"
      register: result
      ignore_errors: true

    - name: Create Virtual Network Templates
      shell: |
        onevnet create /home/manage/wan_net.tmpl 
        onevnet create /home/manage/lan_net.tmpl
      when: result| failed

    - name: Check if Images exist
      become_user: oneadmin
      become_method: sudo
      shell: "oneimage list --list NAME | grep 'iTaas1'"
      register: result
      ignore_errors: true

    - name: Create Images
      shell: | 
        oneimage create -d 1 --name iTaas1 --source '/var/lib/one/datastores/1/f7459d3fe8f0cc272fe9cd6a9b6edab3' --size 6239M --driver qcow2 --type OS
        oneimage create -d 1 --name iTaas2 --source '/var/lib/one/datastores/1/39745246d90aab23c3434be0c9e159c5' --size 2203M --driver qcow2 --type OS
      when: result| failed

    - name: Check if Templates exist
      become_user: oneadmin
      become_method: sudo
      shell: "onetemplate list --list NAME | grep 'iTaasTempl1'"
      register: result
      ignore_errors: true

    - name: Create Templates
      shell: |
        onetemplate create --name 'iTaasTempl1'  --memory '2g' --cpu 1 --vnc --nic 'Public,Private' --net_context --disk 'iTaas1'
        onetemplate create --name 'iTaasTempl2'  --memory '2g' --cpu 1 --vnc --nic 'Public,Private' --net_context --disk 'iTaas2'
      when: result| failed

    - name: Check if VMs exist
      become_user: oneadmin
      become_method: sudo
      shell: "onevm list --list NAME | grep 'iTaasMachine1'"
      register: result
      ignore_errors: true

    - name: Deploy VMs
      shell: |
        onetemplate instantiate 'iTaasTempl1' --name 'iTaasMachine1' 
        onetemplate instantiate 'iTaasTempl2' --name 'iTaasMachine2'
      when: result| failed
